version: '3'

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - 8000
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      # - "443:443"  # If using SSL
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
